Fix error: warning: zoxide-0.9.9-2.1 is up to date -- skipping
resolving dependencies...
looking for conflicting packages...
:: tree-sitter-cli-0.26.8-1.1 and
tree-sitter-cli-git-0.26.8.r206.g8178cfddd-1 are in conflict. Remove
tree-sitter-cli-git? [y/N]
error: unresolvable package conflicts detected
error: failed to prepare transaction (conflicting dependencies)
:: tree-sitter-cli-0.26.8-1.1 and
tree-sitter-cli-git-0.26.8.r206.g8178cfddd-1 are in conflict